# Generated by Django 3.1.2 on 2020-10-31 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_studetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
